#!/bin/bash

# Get the current date in the format YYYY-MM-DD
current_date=$(date +"%Y-%m-%d")

# Define the source and destination directories
downloads_dir="$HOME/Downloads"
destination_dir="$downloads_dir/Archive/$current_date"

# Create the destination directory if it doesn't exist
mkdir -p "$destination_dir"
echo -n "cleaning up..."
# Move files from the Downloads directory to the current date's folder silently
find "$downloads_dir" -type f -exec mv {} "$destination_dir" \; >/dev/null 2>&1
echo "done"